### ISSUE TITLE
Repository caption states it's OBSOLETE

### ISSUE THREAD

**Issue by hugolm84** [MaxKellermann/cegcc-build#3]
Hi! 

Thanks for working on this project! The caption on the repository says its obsolete, is this true? Are there any alternative? 
It seems like you are actively working on it, and if that the case, perhaps replace/remove the OBSOLETE word?

Best

**Comment by MaxKellermann** [comment]
I don't use this repository, because I build the toolchain manually, but I updated it last year because somebody found it useful... I'm not sure how many users of cegcc there still are and how they build it. (I havn't been using it for several years, but I get emails about it from time to time.)

**Comment by hugolm84** [comment]
Ok, I understand! I currently building it and it seems to work fine... :) I'm very interested in trying it out and to see if I can get a working example on WEC2013.
